"""
Django settings for tutorflow project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url


def env(name: str, default=None):
    """Lightweight environment helper (avoids adding django-environ)."""
    value = os.environ.get(name)
    if value is None:
        return default
    return value


def env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default=None):
    value = os.environ.get(name)
    if value is None:
        return default or []
    # Support comma-separated lists
    return [item.strip() for item in value.split(",") if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", default=False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "dev-insecure-secret-key"
    else:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured(
            "SECRET_KEY environment variable must be set in production (DEBUG=False)."
        )

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS")
if not ALLOWED_HOSTS:
    if DEBUG:
        ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
    else:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured(
            "ALLOWED_HOSTS environment variable must be set in production (DEBUG=False). "
            "Set ALLOWED_HOSTS with your domain(s), e.g., "
            "ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com or "
            "ALLOWED_HOSTS=*.railway.app"
        )

CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", default=[])


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    # TutorFlow apps
    "apps.core",
    "apps.students",
    "apps.contracts",
    "apps.lessons",
    "apps.blocked_times",
    "apps.lesson_plans",
    "apps.ai",
    "apps.billing",
    "apps.portal",
    "apps.meeting",
    "channels",
]

_REDIS_URL = os.environ.get("REDIS_URL")
if _REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [
                    {
                        "address": _REDIS_URL,
                        "socket_timeout": None,
                        "socket_connect_timeout": 5,
                        "socket_keepalive": True,
                    }
                ],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
            "CAPACITY": 1000,
        }
    }

ASGI_APPLICATION = "tutorflow.asgi.application"

# ICE servers for WebRTC
# TURN auf ai-server (46.224.151.16:3478). Credential über Env-Var überschreibbar.
_TURN_URL = env("TURN_URL", default="turn:46.224.151.16:3478")
_TURN_USER = env("TURN_USER", default="preceptly")
_TURN_CREDENTIAL = env("TURN_CREDENTIAL")
if not _TURN_CREDENTIAL:
    if DEBUG or "test" in sys.argv:
        _TURN_CREDENTIAL = "dummy-turn-credential-for-development-only"
    else:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured(
            "TURN_CREDENTIAL environment variable must be set in production (DEBUG=False)."
        )

MEETING_ICE_SERVERS = [
    {"urls": "stun:stun.l.google.com:19302"},
    {"urls": "stun:stun1.l.google.com:19302"},
    {"urls": _TURN_URL, "username": _TURN_USER, "credential": _TURN_CREDENTIAL},
    {
        "urls": _TURN_URL.replace("turn:", "turn:") + "?transport=tcp",
        "username": _TURN_USER,
        "credential": _TURN_CREDENTIAL,
    },
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "apps.core.middleware.CanonicalDomainMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tutorflow.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "apps.core.context_processors.unread_portal_messages",
                "apps.core.context_processors.demo_context",
            ],
        },
    },
]

WSGI_APPLICATION = "tutorflow.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = env("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=not DEBUG)
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Cache for rate limiting – use Redis when available (same URL as Channels layer),
# fall back to LocMemCache in local dev without Redis.
if _REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

# Trusted reverse-proxy IPs/CIDRs for IP-based rate limiting in auth_throttle.
# Supports individual IPs and CIDR notation (e.g. "10.0.0.0/8").
# On Railway (and similar PaaS), set TRUSTED_PROXIES to the internal proxy
# range so X-Forwarded-For is evaluated and rate limits apply per real client IP.
TRUSTED_PROXIES = env_list("TRUSTED_PROXIES", default=["100.64.0.0/10"])

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "de"

# Supported languages (de first = default fallback)
LANGUAGES = [
    ("de", "Deutsch"),
    ("en", "English"),
]

# Timezone: Europe/Berlin
TIME_ZONE = "Europe/Berlin"

# Authentication
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/login/"

USE_I18N = True
USE_L10N = True

USE_TZ = True

# Locale paths
LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (User-uploaded files)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

_testing = "test" in sys.argv or (bool(sys.argv) and "pytest" in sys.argv[0])

# WhiteNoise serves compressed+hashed static files in production.
# In test runs collectstatic hasn't run so no manifest exists — use plain storage.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG and not _testing
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=not DEBUG and not _testing)
# Production: secure cookies and HTTPOnly. Railway uses HTTPS (X-Forwarded-Proto).
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", default=not DEBUG)
SESSION_COOKIE_HTTPONLY = True
# CSRF_COOKIE_HTTPONLY=False: JS reads CSRF from cookie/meta for AJAX; Django expects it in header.
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

if not DEBUG:
    SECURE_HSTS_SECONDS = int(env("SECURE_HSTS_SECONDS", default="31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", default=False)
    # Trust X-Forwarded-Proto so build_absolute_uri yields https behind Railway/reverse proxy
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    # Security headers (SecurityMiddleware adds X-Content-Type-Options; we add more via custom)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

# AI/LLM Configuration
# Diese Werte sollten über Umgebungsvariablen gesetzt werden
# Beispiel: export LLM_API_KEY="your-key-here"
LLM_API_BASE_URL = os.environ.get("LLM_API_BASE_URL", "https://api.anthropic.com")
LLM_API_KEY = os.environ.get("LLM_API_KEY", "")
LLM_MODEL_NAME = os.environ.get("LLM_MODEL_NAME", "claude-haiku-4-5-20251001")
LLM_TIMEOUT_SECONDS = int(os.environ.get("LLM_TIMEOUT_SECONDS", "30"))

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "stream": sys.stdout,  # Use stdout for better visibility in Railway/Gunicorn logs
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "tutorflow.log",
            "formatter": "verbose",
        },
        "mail_admins": {
            "class": "django.utils.log.AdminEmailHandler",
            "level": "ERROR",
            "include_html": False,
        },
    },
    "loggers": {
        "apps.ai": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "apps.lessons.email_service": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "apps.lessons.views_booking": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console", "mail_admins"],
            "level": "INFO",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",  # Always INFO to see email logs
    },
}

# Create logs directory if it doesn't exist
logs_dir = BASE_DIR / "logs"
logs_dir.mkdir(exist_ok=True)

# Email configuration
# Use custom timeout backend for SMTP to prevent hanging
email_backend_setting = env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
if email_backend_setting == "django.core.mail.backends.smtp.EmailBackend":
    # Automatically use timeout backend for SMTP
    EMAIL_BACKEND = "apps.lessons.email_backend.TimeoutSMTPEmailBackend"
else:
    EMAIL_BACKEND = email_backend_setting

EMAIL_HOST = env("EMAIL_HOST", default="smtp.mail.me.com")
EMAIL_PORT = int(env("EMAIL_PORT", default="587"))
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", default=False)

# Validate that TLS and SSL are not both enabled
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    import warnings

    warnings.warn(
        "EMAIL_USE_TLS and EMAIL_USE_SSL are both True. "
        "They are mutually exclusive. Disabling EMAIL_USE_SSL.",
        UserWarning,
        stacklevel=2,
    )
    EMAIL_USE_SSL = False

EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="andreaseirich2004@icloud.com")
INVOICE_FROM_EMAIL = env("INVOICE_FROM_EMAIL", default="rechnung@andicode.de")
SERVER_EMAIL = env("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)
# Email timeout configuration (for TimeoutSMTPEmailBackend)
# Socket timeout for SMTP connections (prevents hanging)
EMAIL_TIMEOUT = int(env("EMAIL_TIMEOUT", default="10"))  # 10 seconds default

# Email notification settings
NOTIFICATION_EMAIL = env("NOTIFICATION_EMAIL", default="")
ADMIN_NOTIFICATION_EMAIL = env("ADMIN_NOTIFICATION_EMAIL", default="info@preceptly.de")
ADMINS = [(ADMIN_NOTIFICATION_EMAIL, ADMIN_NOTIFICATION_EMAIL)]
SITE_URL = env("SITE_URL", default="https://preceptly.de")

# Stripe (subscription payments for Premium)
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY", default="")
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default="")
STRIPE_PRICE_ID_MONTHLY = env("STRIPE_PRICE_ID_MONTHLY", default="")  # legacy (= Pro)
STRIPE_PRICE_ID_YEARLY = env("STRIPE_PRICE_ID_YEARLY", default="")
STRIPE_PRICE_ID_STARTER = env("STRIPE_PRICE_ID_STARTER", default="")
STRIPE_PRICE_ID_PRO = env("STRIPE_PRICE_ID_PRO", default="")
STRIPE_PRICE_ID_BUSINESS = env("STRIPE_PRICE_ID_BUSINESS", default="")
STRIPE_PORTAL_RETURN_URL = env("STRIPE_PORTAL_RETURN_URL", default="")
STRIPE_CHECKOUT_SUCCESS_URL = env("STRIPE_CHECKOUT_SUCCESS_URL", default="")
STRIPE_CHECKOUT_CANCEL_URL = env("STRIPE_CHECKOUT_CANCEL_URL", default="")

# Whitelist of all known premium price IDs. Unknown prices must never grant a
# paid tier (see _handle_subscription_created_or_updated / _price_id_to_tier).
# Defaults to every configured tier price; override via comma-separated env var.
STRIPE_PREMIUM_PRICE_IDS = env_list(
    "STRIPE_PREMIUM_PRICE_IDS",
    default=[
        price_id
        for price_id in (
            STRIPE_PRICE_ID_MONTHLY,
            STRIPE_PRICE_ID_YEARLY,
            STRIPE_PRICE_ID_STARTER,
            STRIPE_PRICE_ID_PRO,
            STRIPE_PRICE_ID_BUSINESS,
        )
        if price_id
    ],
)

STRIPE_ENABLED = bool(
    STRIPE_SECRET_KEY and STRIPE_WEBHOOK_SECRET and (STRIPE_PRICE_ID_MONTHLY or STRIPE_PRICE_ID_PRO)
)
STRIPE_PREMIUM_CHECKOUT_ENABLED = bool(
    STRIPE_SECRET_KEY and (STRIPE_PRICE_ID_MONTHLY or STRIPE_PRICE_ID_PRO)
)

# e-recht24 Rechtstexte API
ERECHT24_API_KEY = env("ERECHT24_API_KEY", default="")
ERECHT24_PLUGIN_KEY = env("ERECHT24_PLUGIN_KEY", default="")
ERECHT24_PUSH_SECRET = env("ERECHT24_PUSH_SECRET", default="")
ERECHT24_CLIENT_ID = env("ERECHT24_CLIENT_ID", default="")

# e-recht24 Widerrufsbutton webhook (separate feature and secret from the
# legal text push above). HMAC-SHA256 signature over the raw request body.
# If unset, the webhook endpoint fails closed with 503 instead of accepting
# unsigned requests (see views_erecht24_revocation.py).
ERECHT24_REVOCATION_WEBHOOK_SECRET = env("ERECHT24_REVOCATION_WEBHOOK_SECRET", default="")

X_FRAME_OPTIONS = "DENY"

# security.W021: SECURE_HSTS_PRELOAD not set to True.
# HSTS preloading is a hard-to-reverse, browser-level commitment (removal takes
# months). We deliberately leave it disabled until we are ready to opt in.
SILENCED_SYSTEM_CHECKS = ["security.W021"]
