# Generated by Django 6.0.4 on 2026-06-18 09:35

from django.db import migrations, models


def normalize_stripe_subscription_id(apps, schema_editor):
    UserProfile = apps.get_model("core", "UserProfile")
    UserProfile.objects.filter(stripe_subscription_id="").update(stripe_subscription_id=None)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_expense_business_use_percent"),
    ]

    operations = [
        migrations.RunPython(normalize_stripe_subscription_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userprofile",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Subscription ID",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="travel_policy",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Time-dependent travel policy for on-site booking: enabled, buffer_rules (weekday, start_time, end_time, buffer_minutes), no_go_windows. Weekday 0=Monday.",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tutor_no_show_pay_percent",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="TutorSpace, session marked 'tutor did not show (student waited)': share of the usual lesson amount you still keep. The rest is not paid, and the usual amount is deducted (net ≈ −(100−this)% of usual pay). 0%% = full deduction (−100%% of usual pay); 100%% = full usual pay (no deduction).",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tutorspace_tier_count_from",
            field=models.DateField(
                blank=True,
                help_text="TutorSpace pay tiers (13/14 € …): if set, only lessons on or after this date count toward cumulative hours. Empty = all past TutorSpace lessons count (can make the preview look ‘too high’ if you have many older sessions).",
                null=True,
            ),
        ),
    ]
