# Generated by Django 6.0.4 on 2026-06-18 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_stripe_subscription_id_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_premium",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Does the user have premium access?"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="next_invoice_number",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Next sequential invoice number (Premium only).",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tutor_no_show_pay_percent",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="TutorSpace, session marked 'tutor did not show (student waited)': share of the usual lesson amount you still keep. The rest is not paid, and the usual amount is deducted (net ≈ −(100−this)% of usual pay). 0%% = full deduction (−100%% of usual pay); 100%% = full usual pay (no deduction).",
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
