# Generated by Django 6.0.4 on 2026-06-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_userprofile_is_premium_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="subscription_tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("starter", "Starter"),
                    ("pro", "Pro"),
                    ("business", "Business"),
                ],
                db_index=True,
                default="free",
                help_text="Current subscription tier (free/starter/pro/business)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_premium",
            field=models.BooleanField(
                db_index=True, default=False, help_text="True for Pro and Business tiers"
            ),
        ),
    ]
