# Generated by Django 6.0.4 on 2026-06-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_add_subscription_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avv_accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user explicitly accepted AGB, AVV, and Datenschutzerklärung.",
                null=True,
            ),
        ),
    ]
