# Generated by Django 6.0.4 on 2026-06-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_add_avv_accepted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(default="Europe/Berlin", max_length=64, verbose_name="Zeitzone"),
        ),
    ]
