# Generated by Django 6.0.4 on 2026-06-25 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_add_requestlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="premium_source",
            new_name="subscription_source",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_premium",
        ),
    ]
