# Generated by Django 6.0.6 on 2026-07-11 17:59

from django.db import migrations, models
from django.db.models import F


def backfill_processed_at(apps, schema_editor):
    # Rows created before this field existed were only stored after Stripe
    # delivered the event; under the old semantics their existence meant
    # "already handled". Mark them processed so late retries are not replayed.
    StripeWebhookEvent = apps.get_model("core", "StripeWebhookEvent")
    StripeWebhookEvent.objects.filter(processed_at__isnull=True).update(
        processed_at=F("created_at")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_update_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripewebhookevent",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, help_text="Set only after successful processing", null=True
            ),
        ),
        migrations.RunPython(backfill_processed_at, migrations.RunPython.noop),
    ]
