# Generated by Django 6.0.6 on 2026-07-12 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_stripewebhookevent_processed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RevocationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "revo_id",
                    models.CharField(
                        help_text="e-recht24 revocation ID (idempotency key for webhook retries)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("customer_name", models.CharField(blank=True, max_length=200)),
                ("customer_email", models.CharField(blank=True, max_length=254)),
                ("order_number", models.CharField(blank=True, max_length=100)),
                ("customer_number", models.CharField(blank=True, max_length=100)),
                ("relevant_service", models.CharField(blank=True, max_length=200)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_confirmation", "Pending confirmation"),
                            ("confirmed_cancelled", "Confirmed and cancelled"),
                            ("no_match", "No matching account"),
                            ("ambiguous_match", "Ambiguous match"),
                            ("expired", "Confirmation token expired"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "confirmation_token",
                    models.CharField(
                        blank=True,
                        help_text="Set to None once used or expired so the link cannot be reused",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("confirmation_token_created_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revocation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Revocation Request",
                "verbose_name_plural": "Revocation Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
