# Generated by Django 6.0.6 on 2026-07-30 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_remove_userprofile_institute_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="referral_code",
            field=models.CharField(
                blank=True,
                help_text="This user's own code to share for referrals.",
                max_length=12,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="referral_free_months_pending",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Free months earned as a referrer, not yet applied as Stripe balance credit (e.g. because this user has no Stripe customer/price yet).",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="referral_reward_granted",
            field=models.BooleanField(
                default=False,
                help_text="True once this user's first paid invoice has granted their referrer's reward. Prevents granting the reward again on later renewal invoices.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user whose referral code was used at registration, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_signups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="trial_used",
            field=models.BooleanField(
                default=False,
                help_text="True once the user's one-time free trial month has started.",
            ),
        ),
    ]
