# Generated by Django 6.1.1 on 2026-09-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="portal_buffer_hint_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
