# Generated by Django 6.1.1 on 2026-09-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_userprofile_portal_buffer_hint_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="withdrawal_waiver_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
