# Generated by Django 6.1.1 on 2026-09-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_userprofile_withdrawal_waiver_accepted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True, help_text="When the account email was confirmed via link.", null=True
            ),
        ),
    ]
