# Generated by Django 6.1.1 on 2026-10-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_userprofile_email_verified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_portal_change_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_portal_change_push",
            field=models.BooleanField(default=True),
        ),
    ]
