# Generated by Django 6.1.1 on 2026-10-04 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_portal_cancellations"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="min_gap_minutes",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Minimum minutes between two appointments and between an appointment and a blocked time. 0 = none.",
                validators=[django.core.validators.MaxValueValidator(240)],
            ),
        ),
    ]
