"""
Regression test: creating a recurring BlockedTime via the create form must not
500 with a NOT NULL user_id IntegrityError.

Root cause: BlockedTimeCreateView.form_valid() built and saved the recurring
occurrences via RecurringBlockedTimeService, then unconditionally fell through
to super().form_valid(form) - which saved the original single-day
form.instance a second time. That instance never had .user assigned on the
success ("created > 0") path, so the extra save violated the not-null
constraint on blocked_times_blockedtime.user_id.
"""

from datetime import timedelta

from django.contrib.auth.models import User
from django.test import Client, TestCase
from django.urls import reverse
from django.utils import timezone

from apps.blocked_times.models import BlockedTime


def _next_future_datetime(hour, minute):
    """A datetime a week out, at a fixed time of day - always in the future
    regardless of when the suite runs (avoids hardcoded-date bit-rot)."""
    from datetime import datetime

    future_date = timezone.localdate() + timedelta(days=7)
    return timezone.make_aware(
        datetime(future_date.year, future_date.month, future_date.day, hour, minute)
    )


class RecurringBlockedTimeCreateRegressionTest(TestCase):
    def setUp(self):
        self.client = Client()
        self.tutor = User.objects.create_user(username="tutor", password="test")
        self.client.force_login(self.tutor)

    def _post_data(self, start, end, weekday_code):
        return {
            "title": "Straßeneinsatz",
            "description": "",
            "start_datetime": start.strftime("%Y-%m-%dT%H:%M"),
            "end_datetime": end.strftime("%Y-%m-%dT%H:%M"),
            "is_recurring": "on",
            "recurrence_type": "weekly",
            "recurrence_end_date": (start + timedelta(days=14)).strftime("%Y-%m-%d"),
            "recurrence_weekdays": [weekday_code],
        }

    def test_create_recurring_blocked_time_does_not_500(self):
        """Reproduces the reported bug: creating a weekly recurring blocked
        time (with at least one matching weekday, so occurrences are actually
        generated) must redirect (302), not crash with a 500."""
        start = _next_future_datetime(6, 0)
        end = _next_future_datetime(12, 0)
        weekday_code = str(start.weekday())  # matches the start day so it recurs

        response = self.client.post(
            reverse("blocked_times:create"),
            self._post_data(start, end, weekday_code),
        )

        self.assertEqual(response.status_code, 302)

        created = BlockedTime.objects.filter(user=self.tutor, title="Straßeneinsatz")
        self.assertGreater(created.count(), 0)
        # No orphaned row without a user should have been created either.
        self.assertEqual(BlockedTime.objects.filter(user__isnull=True).count(), 0)

    def test_no_duplicate_first_occurrence_row(self):
        """The original single-day form instance must not be saved a second
        time in addition to the rows generated by the recurring service."""
        start = _next_future_datetime(6, 0)
        end = _next_future_datetime(12, 0)
        weekday_code = str(start.weekday())

        self.client.post(
            reverse("blocked_times:create"),
            self._post_data(start, end, weekday_code),
        )

        first_day_rows = BlockedTime.objects.filter(
            user=self.tutor,
            title="Straßeneinsatz",
            start_datetime=start,
            end_datetime=end,
        )
        self.assertEqual(first_day_rows.count(), 1)
