# Generated by Django 6.0.4 on 2026-06-18 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0011_alter_invoice_total_amount_alter_invoiceitem_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                help_text="Duration in minutes (copy)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
