# Generated by Django 6.0.4 on 2026-06-18 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0012_alter_invoiceitem_duration_minutes"),
        ("contracts", "0012_alter_contract_options_and_more"),
        ("lessons", "0016_alter_session_tutor_no_show"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="invoice_period_end_gte_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lesson__isnull", False)),
                fields=("invoice", "lesson"),
                name="uniq_invoiceitem_invoice_lesson",
            ),
        ),
    ]
