# Generated by Django 6.0.8 on 2026-08-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0013_safe_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount for this item (negative for deductions, e.g. a tutor no-show).",
                max_digits=10,
            ),
        ),
    ]
