# Generated by Django 6.1.1 on 2026-09-28 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0014_alter_invoiceitem_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="cancels",
            field=models.OneToOneField(
                blank=True,
                help_text="For a cancellation invoice: the invoice it cancels",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cancellation",
                to="billing.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                help_text="Invoice status",
                max_length=20,
            ),
        ),
    ]
