# Generated by Django 6.0.4 on 2026-06-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0003_portal_contract_fks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentstudentlink",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="portalmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="portalmessage",
            name="read_by_portal",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="portalmessage",
            name="read_by_tutor",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="portaluser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="progressnote",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="studentportallink",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
