# Generated by Django 6.0.4 on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0004_alter_parentstudentlink_id_alter_portalmessage_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentportallink",
            name="invite_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parentstudentlink",
            name="invite_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
