# Generated by Django 6.0.6 on 2026-07-14 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0006_password_reset_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentstudentlink",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_links",
                to="portal.portaluser",
            ),
        ),
    ]
