# Generated by Django 6.0.8 on 2026-09-04 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0008_migrate_student_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="portaluser",
            name="ical_feed_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unguessable token identifying this user's read-only calendar feed URL - the token itself is the auth, no login required.",
                unique=True,
            ),
        ),
    ]
