# Generated by Django 6.0.4 on 2026-06-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meeting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingroom",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
