# Generated by Django 6.0.4 on 2026-06-18 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lesson_plans", "0004_lessonplan_contract_fk"),
        ("lessons", "0016_alter_session_tutor_no_show"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="lessonplan",
            new_name="lesson_plan_contrac_defc78_idx",
            old_name="lesson_plan_contract_idx",
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="duration_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="grade_level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                db_column="lesson_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_plans",
                to="lessons.session",
            ),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="llm_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="subject",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="topic",
            field=models.CharField(max_length=200),
        ),
    ]
