# Generated by Django 6.0.4 on 2026-06-18 11:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0011_contract_remove_student_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={
                "ordering": ["-start_date", "last_name", "first_name"],
                "verbose_name": "Schüler",
                "verbose_name_plural": "Schüler",
            },
        ),
        migrations.AlterField(
            model_name="contract",
            name="booking_code_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA-256 hash of the public booking code (never store plaintext)",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="booking_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="has_monthly_planning_limit",
            field=models.BooleanField(default=True, verbose_name="monthly planning limit"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="hourly rate",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="institute",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="institute"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="is_adult",
            field=models.BooleanField(
                default=False,
                help_text="Wenn aktiviert, wird kein Eltern-Portal-Zugang angeboten.",
                verbose_name="Erwachsener Schüler",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="start_date",
            field=models.DateField(verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="unit_duration_minutes",
            field=models.PositiveIntegerField(
                default=60,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="unit duration (minutes)",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="user",
            field=models.ForeignKey(
                help_text="Tutor who owns this contract",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="tutor",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="working_hours",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="contractmonthlyplan",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_plans",
                to="contracts.contract",
            ),
        ),
        migrations.AlterField(
            model_name="contractmonthlyplan",
            name="month",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="contractmonthlyplan",
            name="planned_units",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contractmonthlyplan",
            name="year",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="institutetierconfig",
            name="institute_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="institutetierconfig",
            name="tiers",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="institutetierconfig",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institute_tier_configs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
