# Generated by Django 6.0.6 on 2026-07-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0013_contract_parent_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutetierconfig",
            name="unpaid_on_tutor_no_show",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, lessons marked as tutor no-show are billed with 0 €.",
                verbose_name="no billing on tutor no-show",
            ),
        ),
    ]
