# Generated by Django 6.0.6 on 2026-07-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0015_backfill_tier_rates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutetierconfig",
            name="tiers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
