# Generated by Django 6.1.1 on 2026-10-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0020_remove_contract_institute"),
    ]

    operations = [
        migrations.AddField(
            model_name="institute",
            name="tier_count_mode",
            field=models.CharField(
                choices=[
                    ("duration", "By duration (60 minutes = 1)"),
                    ("started_hours", "By unit (every started hour = 1)"),
                ],
                default="duration",
                help_text="By unit: a lesson of 30 or 60 minutes counts as 1, one of 120 minutes as 2. Pay always follows the duration (30 minutes earn half the hourly rate). This only decides how fast you reach the next tier.",
                max_length=20,
                verbose_name="how lessons count toward the tiers",
            ),
        ),
        migrations.AddField(
            model_name="institute",
            name="tier_count_offset",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Hours or units the institute had already counted before the lessons recorded here. They are added to the counter.",
                verbose_name="start value for the tier counter",
            ),
        ),
    ]
