# Generated by Django 6.1.1 on 2026-10-04 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0021_tier_count_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="default_travel_time_after_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Pre-filled for new lessons of this student. You can change it for each lesson.",
                validators=[django.core.validators.MaxValueValidator(480)],
                verbose_name="default travel time after (minutes)",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="default_travel_time_before_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Pre-filled for new lessons of this student. You can change it for each lesson.",
                validators=[django.core.validators.MaxValueValidator(480)],
                verbose_name="default travel time before (minutes)",
            ),
        ),
    ]
