# Generated by Django 6.0.8 on 2026-09-03 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("icloud", "iCloud"), ("google", "Google")], max_length=20
                    ),
                ),
                ("caldav_url", models.URLField(blank=True, max_length=500)),
                ("caldav_username", models.CharField(blank=True, max_length=255)),
                ("encrypted_password", models.BinaryField(blank=True, null=True)),
                ("sync_enabled", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Connection",
                "verbose_name_plural": "Calendar Connections",
            },
        ),
        migrations.CreateModel(
            name="ExternalCalendarEventMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("external_uid", models.CharField(max_length=255)),
                ("external_etag", models.CharField(blank=True, max_length=255)),
                (
                    "local_synced_at",
                    models.DateTimeField(
                        help_text="Local object's updated_at as of the last successful sync."
                    ),
                ),
                (
                    "external_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="External event's last-modified as of the last successful sync.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_mappings",
                        to="calendar_sync.calendarconnection",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "verbose_name": "External Calendar Event Mapping",
                "verbose_name_plural": "External Calendar Event Mappings",
            },
        ),
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("local_snapshot", models.JSONField()),
                ("external_snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("local", "Keep Preceptly version"),
                            ("external", "Keep external version"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="calendar_sync.calendarconnection",
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="calendar_sync.externalcalendareventmapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Conflict",
                "verbose_name_plural": "Sync Conflicts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="externalcalendareventmapping",
            index=models.Index(
                fields=["content_type", "object_id"], name="calendar_sy_content_2b5eed_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalcalendareventmapping",
            constraint=models.UniqueConstraint(
                fields=("connection", "content_type", "object_id"),
                name="unique_mapping_per_local_object",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalcalendareventmapping",
            constraint=models.UniqueConstraint(
                fields=("connection", "external_uid"), name="unique_mapping_per_external_event"
            ),
        ),
    ]
