# Generated by Django 6.0.8 on 2026-09-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_sync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarconnection",
            name="last_sync_summary",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Counts from the most recent sync run (pushed/pulled/imported/deleted/conflicts/errors), shown on the settings page so the tutor can see what actually happened, not just a status dot.",
            ),
        ),
    ]
