# Generated by Django 6.0.8 on 2026-09-04 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_sync", "0002_calendarconnection_last_sync_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncedCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_calendar_url", models.URLField(max_length=500)),
                ("display_name", models.CharField(blank=True, max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("sessions_target", "Sessions are pushed here"),
                            ("blocked_time_source", "Blocked times are imported from here"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synced_calendars",
                        to="calendar_sync.calendarconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synced Calendar",
                "verbose_name_plural": "Synced Calendars",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("connection", "external_calendar_url", "role"),
                        name="unique_calendar_role_per_connection",
                    )
                ],
            },
        ),
    ]
