# Generated by Django 6.1.1 on 2026-09-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_sync", "0003_syncedcalendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncedcalendar",
            name="title_template",
            field=models.CharField(
                blank=True,
                default="Nachhilfe - {student}",
                help_text="Only used for sessions_target: how a pushed Session's title is built. Placeholders: {student} (full name), {subject}.",
                max_length=200,
            ),
        ),
    ]
