# Generated by Django 6.0.4 on 2026-06-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0015_session_homework_meeting_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="recurring_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Recurring series this session was generated from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_sessions",
                to="lessons.recurringsession",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="tutor_no_show",
            field=models.BooleanField(
                default=False,
                help_text="Tutor did not attend while the student was waiting. TutorSpace: pay/deduction per your settings. Abacus: lesson is not billed (0). Other contracts: no effect on amount.",
            ),
        ),
    ]
