# Generated by Django 6.0.4 on 2026-06-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0015_session_homework_meeting_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="tutor_no_show",
            field=models.BooleanField(
                default=False,
                help_text="Tutor did not attend while the student was waiting. TutorSpace: pay/deduction per your settings. Abacus: lesson is not billed (0). Other contracts: no effect on amount.",
            ),
        ),
    ]
