# Generated by Django 6.0.4 on 2026-06-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0012_alter_contract_options_and_more"),
        ("lessons", "0016_alter_session_tutor_no_show"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ["cancelled", "paid"]), _negated=True),
                    ("tutor_no_show", False),
                    _connector="OR",
                ),
                name="session_no_show_only_if_not_cancelled_paid",
            ),
        ),
    ]
