# Generated by Django 6.0.8 on 2026-08-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0017_safe_session_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="tutor_no_show",
            field=models.BooleanField(
                default=False,
                help_text="Tutor did not attend while the student was waiting. Depending on the institute's no-show rule, this may reduce or zero out the billed amount; contracts without such a rule are unaffected.",
            ),
        ),
    ]
