# Generated by Django 6.1.1 on 2026-09-29 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0018_alter_session_tutor_no_show"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringsession",
            name="booked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Account that created the series",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recurringsession",
            name="created_via",
            field=models.CharField(
                blank=True, help_text="Source: portal_series or tutor", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="booked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Account that booked the session (tutor or portal account)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="created_via",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Source: portal_booking, portal_series or tutor",
                max_length=20,
                null=True,
            ),
        ),
    ]
