# Generated by Django 6.1.1 on 2026-10-02 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0021_tier_count_mode"),
        ("lessons", "0019_booked_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CancelledSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True, default="")),
                ("was_series", models.BooleanField(default=False)),
                ("booked_at", models.DateTimeField(blank=True, null=True)),
                ("created_via", models.CharField(blank=True, max_length=20, null=True)),
                ("cancelled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cancelled_via",
                    models.CharField(
                        choices=[("portal", "Portal"), ("portal_series", "Portal (ganze Serie)")],
                        max_length=20,
                    ),
                ),
                (
                    "booked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancelled_sessions",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "ordering": ["-cancelled_at", "-date", "-start_time"],
                "indexes": [
                    models.Index(
                        fields=["contract", "-cancelled_at"], name="lessons_canc_contract_idx"
                    )
                ],
            },
        ),
    ]
